package GUIDesigning;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Santosh
 */
public class AdditionGUI extends java.awt.Frame {

    /**
     * Creates new form Add
     */
    public AdditionGUI() {
        initComponents();
        setSize(400, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        panel = new javax.swing.JPanel();
        fnum = new javax.swing.JLabel();
        num1 = new javax.swing.JTextField();
        snum = new javax.swing.JLabel();
        num2 = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        add(addbtn);
        addbtn.setBounds(170, 160, 80, 23);

        jLabel3.setText("Result");
        add(jLabel3);
        jLabel3.setBounds(120, 200, 60, 14);
        add(jTextField3);
        jTextField3.setBounds(220, 200, 100, 20);

        panel.setLayout(null);

        fnum.setText("First Num");
        panel.add(fnum);
        fnum.setBounds(50, 20, 70, 14);
        panel.add(num1);
        num1.setBounds(150, 20, 100, 20);

        snum.setText("Second Num");
        panel.add(snum);
        snum.setBounds(50, 60, 70, 14);
        panel.add(num2);
        num2.setBounds(150, 60, 100, 20);

        add(panel);
        panel.setBounds(70, 40, 290, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(num1.getText());
        int b = Integer.parseInt(num2.getText());
        int c = a + b;
        jTextField3.setText("" + c);
        panel.setVisible(false);
    }//GEN-LAST:event_addbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdditionGUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JLabel fnum;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField num2;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel snum;
    // End of variables declaration//GEN-END:variables
}
